language: c
sudo: true
os: osx
osx_image: xcode7.2
before_install:
  - brew update
  - clear
  - export THEOS=/opt/theos

script: "sudo python ./CIScripts/get-pip.py && ./Setup.sh && ./CIScripts/InstallTheos.sh &&./build.py DEBUG && cat STDOUT.log && cat STDERR.log"